ALTER TABLE [dbo].[ItemTag]
    ADD CONSTRAINT [PK_ItemTag] PRIMARY KEY CLUSTERED ([Tag] ASC, [ItemID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

