ALTER TABLE [dbo].[ItemType]
    ADD CONSTRAINT [PK_ItemType] PRIMARY KEY CLUSTERED ([ItemTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

