//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace endnote.Tests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using endnote.Tests.Services;


    public class UserServiceTestCoded : WebTest
    {        
        public UserServiceTestCoded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest(Common.userDomain + "GetUserProfile");
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request1.QueryStringParameters.Add("userId", "aaf9a5a7-1f18-4a2d-b108-3ba3a978bdf6", false, false);
            request1.ValidateResponse += new EventHandler<ValidationEventArgs>(request1_ValidateResponse);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest(Common.userDomain + "GetFriendList");
            request2.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request2.QueryStringParameters.Add("userId", "aaf9a5a7-1f18-4a2d-b108-3ba3a978bdf6", false, false);
            request2.ValidateResponse += new EventHandler<ValidationEventArgs>(request2_ValidateResponse);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest(Common.userDomain + "IsLegalUserName");
            request3.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request3.QueryStringParameters.Add("userName", "testtest", false, false);
            request3.ValidateResponse += new EventHandler<ValidationEventArgs>(request3_ValidateResponse);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest(Common.userDomain + "IsLegalUserName");
            request4.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request4.QueryStringParameters.Add("userName", "userwhichnotexist", false, false);
            request4.ValidateResponse += new EventHandler<ValidationEventArgs>(request4_ValidateResponse);
            yield return request4;
            request4 = null;
        }

        void request1_ValidateResponse(object sender, ValidationEventArgs e)
        {
            Assert.AreEqual(e.Response.BodyString, "{\"Birthday\":\"\\/Date(1288594800000-0700)\\/\",\"Email\":\"test@test.com\",\"NickName\":\"Jeffery\",\"RealName\":\"Jeffery Zhu\",\"UserName\":\"testtest\",\"userID\":\"aaf9a5a7-1f18-4a2d-b108-3ba3a978bdf6\"}");
        }

        void request2_ValidateResponse(object sender, ValidationEventArgs e)
        {
            Assert.AreEqual(e.Response.BodyString, "[]");
        }

        void request3_ValidateResponse(object sender, ValidationEventArgs e)
        {
            Assert.AreEqual(e.Response.BodyString, "false");
        }

        void request4_ValidateResponse(object sender, ValidationEventArgs e)
        {
            Assert.AreEqual(e.Response.BodyString, "true");
        }
    }
}
