//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace endnote.Tests.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Users", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Users : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.FriendInfo[] FriendInfoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.FriendInfo[] FriendInfoes1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAnonymousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActivityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileAliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Applications aspnet_ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Membership aspnet_MembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_MembershipEdRKUs2L aspnet_MembershipReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Profile aspnet_ProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ProfileEdRKUs2L aspnet_ProfileReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Roles[] aspnet_RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.FriendInfo[] FriendInfoes {
            get {
                return this.FriendInfoesField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendInfoesField, value) != true)) {
                    this.FriendInfoesField = value;
                    this.RaisePropertyChanged("FriendInfoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.FriendInfo[] FriendInfoes1 {
            get {
                return this.FriendInfoes1Field;
            }
            set {
                if ((object.ReferenceEquals(this.FriendInfoes1Field, value) != true)) {
                    this.FriendInfoes1Field = value;
                    this.RaisePropertyChanged("FriendInfoes1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymous {
            get {
                return this.IsAnonymousField;
            }
            set {
                if ((this.IsAnonymousField.Equals(value) != true)) {
                    this.IsAnonymousField = value;
                    this.RaisePropertyChanged("IsAnonymous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastActivityDate {
            get {
                return this.LastActivityDateField;
            }
            set {
                if ((this.LastActivityDateField.Equals(value) != true)) {
                    this.LastActivityDateField = value;
                    this.RaisePropertyChanged("LastActivityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredUserName {
            get {
                return this.LoweredUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredUserNameField, value) != true)) {
                    this.LoweredUserNameField = value;
                    this.RaisePropertyChanged("LoweredUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileAlias {
            get {
                return this.MobileAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileAliasField, value) != true)) {
                    this.MobileAliasField = value;
                    this.RaisePropertyChanged("MobileAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Applications aspnet_Applications {
            get {
                return this.aspnet_ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsField, value) != true)) {
                    this.aspnet_ApplicationsField = value;
                    this.RaisePropertyChanged("aspnet_Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReference {
            get {
                return this.aspnet_ApplicationsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsReferenceField, value) != true)) {
                    this.aspnet_ApplicationsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_ApplicationsReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Membership aspnet_Membership {
            get {
                return this.aspnet_MembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_MembershipField, value) != true)) {
                    this.aspnet_MembershipField = value;
                    this.RaisePropertyChanged("aspnet_Membership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_MembershipEdRKUs2L aspnet_MembershipReference {
            get {
                return this.aspnet_MembershipReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_MembershipReferenceField, value) != true)) {
                    this.aspnet_MembershipReferenceField = value;
                    this.RaisePropertyChanged("aspnet_MembershipReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUser {
            get {
                return this.aspnet_PersonalizationPerUserField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PersonalizationPerUserField, value) != true)) {
                    this.aspnet_PersonalizationPerUserField = value;
                    this.RaisePropertyChanged("aspnet_PersonalizationPerUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Profile aspnet_Profile {
            get {
                return this.aspnet_ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ProfileField, value) != true)) {
                    this.aspnet_ProfileField = value;
                    this.RaisePropertyChanged("aspnet_Profile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ProfileEdRKUs2L aspnet_ProfileReference {
            get {
                return this.aspnet_ProfileReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ProfileReferenceField, value) != true)) {
                    this.aspnet_ProfileReferenceField = value;
                    this.RaisePropertyChanged("aspnet_ProfileReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Roles[] aspnet_Roles {
            get {
                return this.aspnet_RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_RolesField, value) != true)) {
                    this.aspnet_RolesField = value;
                    this.RaisePropertyChanged("aspnet_Roles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.FriendInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Applications))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Membership))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Paths))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationAllUsers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Roles))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Profile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Users))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.FriendInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Applications))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Membership))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Paths))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationAllUsers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Roles))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Profile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Users))]
    public partial class EntityObject : endnote.Tests.UserServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendInfo", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class FriendInfo : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FriendIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users aspnet_UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_Users1ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FriendID {
            get {
                return this.FriendIDField;
            }
            set {
                if ((this.FriendIDField.Equals(value) != true)) {
                    this.FriendIDField = value;
                    this.RaisePropertyChanged("FriendID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users1 {
            get {
                return this.aspnet_Users1Field;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_Users1Field, value) != true)) {
                    this.aspnet_Users1Field = value;
                    this.RaisePropertyChanged("aspnet_Users1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_Users1Reference {
            get {
                return this.aspnet_Users1ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_Users1ReferenceField, value) != true)) {
                    this.aspnet_Users1ReferenceField = value;
                    this.RaisePropertyChanged("aspnet_Users1Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReference {
            get {
                return this.aspnet_UsersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersReferenceField, value) != true)) {
                    this.aspnet_UsersReferenceField = value;
                    this.RaisePropertyChanged("aspnet_UsersReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Applications", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Applications : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Membership[] aspnet_MembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Paths[] aspnet_PathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Roles[] aspnet_RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users[] aspnet_UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredApplicationName {
            get {
                return this.LoweredApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredApplicationNameField, value) != true)) {
                    this.LoweredApplicationNameField = value;
                    this.RaisePropertyChanged("LoweredApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Membership[] aspnet_Membership {
            get {
                return this.aspnet_MembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_MembershipField, value) != true)) {
                    this.aspnet_MembershipField = value;
                    this.RaisePropertyChanged("aspnet_Membership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Paths[] aspnet_Paths {
            get {
                return this.aspnet_PathsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PathsField, value) != true)) {
                    this.aspnet_PathsField = value;
                    this.RaisePropertyChanged("aspnet_Paths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Roles[] aspnet_Roles {
            get {
                return this.aspnet_RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_RolesField, value) != true)) {
                    this.aspnet_RolesField = value;
                    this.RaisePropertyChanged("aspnet_Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users[] aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Membership", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Membership : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedPasswordAnswerAttemptCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FailedPasswordAnswerAttemptWindowStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedPasswordAttemptCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FailedPasswordAttemptWindowStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLockoutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastLoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastPasswordChangedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordAnswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PasswordFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordQuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Applications aspnet_ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users aspnet_UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailedPasswordAnswerAttemptCount {
            get {
                return this.FailedPasswordAnswerAttemptCountField;
            }
            set {
                if ((this.FailedPasswordAnswerAttemptCountField.Equals(value) != true)) {
                    this.FailedPasswordAnswerAttemptCountField = value;
                    this.RaisePropertyChanged("FailedPasswordAnswerAttemptCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FailedPasswordAnswerAttemptWindowStart {
            get {
                return this.FailedPasswordAnswerAttemptWindowStartField;
            }
            set {
                if ((this.FailedPasswordAnswerAttemptWindowStartField.Equals(value) != true)) {
                    this.FailedPasswordAnswerAttemptWindowStartField = value;
                    this.RaisePropertyChanged("FailedPasswordAnswerAttemptWindowStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailedPasswordAttemptCount {
            get {
                return this.FailedPasswordAttemptCountField;
            }
            set {
                if ((this.FailedPasswordAttemptCountField.Equals(value) != true)) {
                    this.FailedPasswordAttemptCountField = value;
                    this.RaisePropertyChanged("FailedPasswordAttemptCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FailedPasswordAttemptWindowStart {
            get {
                return this.FailedPasswordAttemptWindowStartField;
            }
            set {
                if ((this.FailedPasswordAttemptWindowStartField.Equals(value) != true)) {
                    this.FailedPasswordAttemptWindowStartField = value;
                    this.RaisePropertyChanged("FailedPasswordAttemptWindowStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLockedOut {
            get {
                return this.IsLockedOutField;
            }
            set {
                if ((this.IsLockedOutField.Equals(value) != true)) {
                    this.IsLockedOutField = value;
                    this.RaisePropertyChanged("IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLockoutDate {
            get {
                return this.LastLockoutDateField;
            }
            set {
                if ((this.LastLockoutDateField.Equals(value) != true)) {
                    this.LastLockoutDateField = value;
                    this.RaisePropertyChanged("LastLockoutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastLoginDate {
            get {
                return this.LastLoginDateField;
            }
            set {
                if ((this.LastLoginDateField.Equals(value) != true)) {
                    this.LastLoginDateField = value;
                    this.RaisePropertyChanged("LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastPasswordChangedDate {
            get {
                return this.LastPasswordChangedDateField;
            }
            set {
                if ((this.LastPasswordChangedDateField.Equals(value) != true)) {
                    this.LastPasswordChangedDateField = value;
                    this.RaisePropertyChanged("LastPasswordChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredEmail {
            get {
                return this.LoweredEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredEmailField, value) != true)) {
                    this.LoweredEmailField = value;
                    this.RaisePropertyChanged("LoweredEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePIN {
            get {
                return this.MobilePINField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePINField, value) != true)) {
                    this.MobilePINField = value;
                    this.RaisePropertyChanged("MobilePIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordAnswer {
            get {
                return this.PasswordAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordAnswerField, value) != true)) {
                    this.PasswordAnswerField = value;
                    this.RaisePropertyChanged("PasswordAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PasswordFormat {
            get {
                return this.PasswordFormatField;
            }
            set {
                if ((this.PasswordFormatField.Equals(value) != true)) {
                    this.PasswordFormatField = value;
                    this.RaisePropertyChanged("PasswordFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordQuestion {
            get {
                return this.PasswordQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordQuestionField, value) != true)) {
                    this.PasswordQuestionField = value;
                    this.RaisePropertyChanged("PasswordQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Applications aspnet_Applications {
            get {
                return this.aspnet_ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsField, value) != true)) {
                    this.aspnet_ApplicationsField = value;
                    this.RaisePropertyChanged("aspnet_Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReference {
            get {
                return this.aspnet_ApplicationsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsReferenceField, value) != true)) {
                    this.aspnet_ApplicationsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_ApplicationsReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReference {
            get {
                return this.aspnet_UsersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersReferenceField, value) != true)) {
                    this.aspnet_UsersReferenceField = value;
                    this.RaisePropertyChanged("aspnet_UsersReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Paths", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Paths : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PathIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Applications aspnet_ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L aspnet_PersonalizationAllUsersReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredPath {
            get {
                return this.LoweredPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredPathField, value) != true)) {
                    this.LoweredPathField = value;
                    this.RaisePropertyChanged("LoweredPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PathId {
            get {
                return this.PathIdField;
            }
            set {
                if ((this.PathIdField.Equals(value) != true)) {
                    this.PathIdField = value;
                    this.RaisePropertyChanged("PathId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Applications aspnet_Applications {
            get {
                return this.aspnet_ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsField, value) != true)) {
                    this.aspnet_ApplicationsField = value;
                    this.RaisePropertyChanged("aspnet_Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReference {
            get {
                return this.aspnet_ApplicationsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsReferenceField, value) != true)) {
                    this.aspnet_ApplicationsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_ApplicationsReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_PersonalizationAllUsers aspnet_PersonalizationAllUsers {
            get {
                return this.aspnet_PersonalizationAllUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PersonalizationAllUsersField, value) != true)) {
                    this.aspnet_PersonalizationAllUsersField = value;
                    this.RaisePropertyChanged("aspnet_PersonalizationAllUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L aspnet_PersonalizationAllUsersReference {
            get {
                return this.aspnet_PersonalizationAllUsersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PersonalizationAllUsersReferenceField, value) != true)) {
                    this.aspnet_PersonalizationAllUsersReferenceField = value;
                    this.RaisePropertyChanged("aspnet_PersonalizationAllUsersReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser[] aspnet_PersonalizationPerUser {
            get {
                return this.aspnet_PersonalizationPerUserField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PersonalizationPerUserField, value) != true)) {
                    this.aspnet_PersonalizationPerUserField = value;
                    this.RaisePropertyChanged("aspnet_PersonalizationPerUser");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_PersonalizationAllUsers", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_PersonalizationAllUsers : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PageSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PathIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Paths aspnet_PathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L aspnet_PathsReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PageSettings {
            get {
                return this.PageSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PageSettingsField, value) != true)) {
                    this.PageSettingsField = value;
                    this.RaisePropertyChanged("PageSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PathId {
            get {
                return this.PathIdField;
            }
            set {
                if ((this.PathIdField.Equals(value) != true)) {
                    this.PathIdField = value;
                    this.RaisePropertyChanged("PathId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Paths aspnet_Paths {
            get {
                return this.aspnet_PathsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PathsField, value) != true)) {
                    this.aspnet_PathsField = value;
                    this.RaisePropertyChanged("aspnet_Paths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L aspnet_PathsReference {
            get {
                return this.aspnet_PathsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PathsReferenceField, value) != true)) {
                    this.aspnet_PathsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_PathsReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_PersonalizationPerUser", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_PersonalizationPerUser : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PageSettingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> PathIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Paths aspnet_PathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L aspnet_PathsReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users aspnet_UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PageSettings {
            get {
                return this.PageSettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PageSettingsField, value) != true)) {
                    this.PageSettingsField = value;
                    this.RaisePropertyChanged("PageSettings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PathId {
            get {
                return this.PathIdField;
            }
            set {
                if ((this.PathIdField.Equals(value) != true)) {
                    this.PathIdField = value;
                    this.RaisePropertyChanged("PathId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Paths aspnet_Paths {
            get {
                return this.aspnet_PathsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PathsField, value) != true)) {
                    this.aspnet_PathsField = value;
                    this.RaisePropertyChanged("aspnet_Paths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L aspnet_PathsReference {
            get {
                return this.aspnet_PathsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_PathsReferenceField, value) != true)) {
                    this.aspnet_PathsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_PathsReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReference {
            get {
                return this.aspnet_UsersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersReferenceField, value) != true)) {
                    this.aspnet_UsersReferenceField = value;
                    this.RaisePropertyChanged("aspnet_UsersReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Roles", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Roles : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoweredRoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Applications aspnet_ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users[] aspnet_UsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoweredRoleName {
            get {
                return this.LoweredRoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoweredRoleNameField, value) != true)) {
                    this.LoweredRoleNameField = value;
                    this.RaisePropertyChanged("LoweredRoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Applications aspnet_Applications {
            get {
                return this.aspnet_ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsField, value) != true)) {
                    this.aspnet_ApplicationsField = value;
                    this.RaisePropertyChanged("aspnet_Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L aspnet_ApplicationsReference {
            get {
                return this.aspnet_ApplicationsReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_ApplicationsReferenceField, value) != true)) {
                    this.aspnet_ApplicationsReferenceField = value;
                    this.RaisePropertyChanged("aspnet_ApplicationsReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users[] aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="aspnet_Profile", Namespace="http://schemas.datacontract.org/2004/07/Notenet.User.Data.Repository", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class aspnet_Profile : endnote.Tests.UserServiceReference.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PropertyValuesBinaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyValuesStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.aspnet_Users aspnet_UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdatedDate {
            get {
                return this.LastUpdatedDateField;
            }
            set {
                if ((this.LastUpdatedDateField.Equals(value) != true)) {
                    this.LastUpdatedDateField = value;
                    this.RaisePropertyChanged("LastUpdatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyNames {
            get {
                return this.PropertyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNamesField, value) != true)) {
                    this.PropertyNamesField = value;
                    this.RaisePropertyChanged("PropertyNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PropertyValuesBinary {
            get {
                return this.PropertyValuesBinaryField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValuesBinaryField, value) != true)) {
                    this.PropertyValuesBinaryField = value;
                    this.RaisePropertyChanged("PropertyValuesBinary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValuesString {
            get {
                return this.PropertyValuesStringField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValuesStringField, value) != true)) {
                    this.PropertyValuesStringField = value;
                    this.RaisePropertyChanged("PropertyValuesString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.aspnet_Users aspnet_Users {
            get {
                return this.aspnet_UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersField, value) != true)) {
                    this.aspnet_UsersField = value;
                    this.RaisePropertyChanged("aspnet_Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L aspnet_UsersReference {
            get {
                return this.aspnet_UsersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.aspnet_UsersReferenceField, value) != true)) {
                    this.aspnet_UsersReferenceField = value;
                    this.RaisePropertyChanged("aspnet_UsersReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_ApplicationsEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_ApplicationsEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_MembershipEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_MembershipEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_ProfileEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_ProfileEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_MembershipEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ProfileEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Users[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Users))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.FriendInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.FriendInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Applications))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Membership[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Membership))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Paths[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Paths))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationAllUsers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_PersonalizationPerUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Roles[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Roles))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.aspnet_Profile))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_UsersEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_UsersEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_MembershipEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ProfileEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L))]
    public partial class EntityReference : endnote.Tests.UserServiceReference.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.UserServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.UserServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ApplicationsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PathsEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_MembershipEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_ProfileEdRKUs2L))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(endnote.Tests.UserServiceReference.EntityReferenceOfaspnet_UsersEdRKUs2L))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_PathsEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_PathsEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfaspnet_PersonalizationAllUsersEdRKUs2L : endnote.Tests.UserServiceReference.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetData", ReplyAction="http://tempuri.org/IUser/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IUser/GetDataUsingDataContractResponse")]
        endnote.Tests.UserServiceReference.CompositeType GetDataUsingDataContract(endnote.Tests.UserServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetFriendList", ReplyAction="http://tempuri.org/IUser/GetFriendListResponse")]
        endnote.Tests.UserServiceReference.aspnet_Users[] GetFriendList(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/IsLegalUserID", ReplyAction="http://tempuri.org/IUser/IsLegalUserIDResponse")]
        bool IsLegalUserID(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserProfile", ReplyAction="http://tempuri.org/IUser/GetUserProfileResponse")]
        endnote.Tests.UserServiceReference.aspnet_Users GetUserProfile(System.Guid userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : endnote.Tests.UserServiceReference.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<endnote.Tests.UserServiceReference.IUser>, endnote.Tests.UserServiceReference.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public endnote.Tests.UserServiceReference.CompositeType GetDataUsingDataContract(endnote.Tests.UserServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public endnote.Tests.UserServiceReference.aspnet_Users[] GetFriendList(System.Guid userId) {
            return base.Channel.GetFriendList(userId);
        }
        
        public bool IsLegalUserID(System.Guid userId) {
            return base.Channel.IsLegalUserID(userId);
        }
        
        public endnote.Tests.UserServiceReference.aspnet_Users GetUserProfile(System.Guid userId) {
            return base.Channel.GetUserProfile(userId);
        }
    }
}
