//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FeedModel", "FK_Item_ItemType", "ItemType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Notenet.Feed.Data.Repository.ItemType), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Notenet.Feed.Data.Repository.Item), true)]
[assembly: EdmRelationshipAttribute("FeedModel", "FK_ItemTag_Item", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Notenet.Feed.Data.Repository.Item), "ItemTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Notenet.Feed.Data.Repository.ItemTag), true)]

#endregion

namespace Notenet.Feed.Data.Repository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FeedEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FeedEntities object using the connection string found in the 'FeedEntities' section of the application configuration file.
        /// </summary>
        public FeedEntities() : base("name=FeedEntities", "FeedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FeedEntities object.
        /// </summary>
        public FeedEntities(string connectionString) : base(connectionString, "FeedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FeedEntities object.
        /// </summary>
        public FeedEntities(EntityConnection connection) : base(connection, "FeedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Item
        {
            get
            {
                if ((_Item == null))
                {
                    _Item = base.CreateObjectSet<Item>("Item");
                }
                return _Item;
            }
        }
        private ObjectSet<Item> _Item;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemTag> ItemTag
        {
            get
            {
                if ((_ItemTag == null))
                {
                    _ItemTag = base.CreateObjectSet<ItemTag>("ItemTag");
                }
                return _ItemTag;
            }
        }
        private ObjectSet<ItemTag> _ItemTag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ItemType> ItemType
        {
            get
            {
                if ((_ItemType == null))
                {
                    _ItemType = base.CreateObjectSet<ItemType>("ItemType");
                }
                return _ItemType;
            }
        }
        private ObjectSet<ItemType> _ItemType;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Item EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemTag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemTag(ItemTag itemTag)
        {
            base.AddObject("ItemTag", itemTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ItemType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItemType(ItemType itemType)
        {
            base.AddObject("ItemType", itemType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FeedModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="itemTypeID">Initial value of the ItemTypeID property.</param>
        /// <param name="externalUrl">Initial value of the ExternalUrl property.</param>
        /// <param name="itemTitle">Initial value of the ItemTitle property.</param>
        /// <param name="itemAbstract">Initial value of the ItemAbstract property.</param>
        /// <param name="itemText">Initial value of the ItemText property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Item CreateItem(global::System.Guid itemID, global::System.Byte itemTypeID, global::System.String externalUrl, global::System.String itemTitle, global::System.String itemAbstract, global::System.String itemText, global::System.DateTime createdDate, global::System.DateTime lastUpdated)
        {
            Item item = new Item();
            item.ItemID = itemID;
            item.ItemTypeID = itemTypeID;
            item.ExternalUrl = externalUrl;
            item.ItemTitle = itemTitle;
            item.ItemAbstract = itemAbstract;
            item.ItemText = itemText;
            item.CreatedDate = createdDate;
            item.LastUpdated = lastUpdated;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Guid _ItemID;
        partial void OnItemIDChanging(global::System.Guid value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ItemTypeID
        {
            get
            {
                return _ItemTypeID;
            }
            set
            {
                OnItemTypeIDChanging(value);
                ReportPropertyChanging("ItemTypeID");
                _ItemTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemTypeID");
                OnItemTypeIDChanged();
            }
        }
        private global::System.Byte _ItemTypeID;
        partial void OnItemTypeIDChanging(global::System.Byte value);
        partial void OnItemTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExternalUrl
        {
            get
            {
                return _ExternalUrl;
            }
            set
            {
                OnExternalUrlChanging(value);
                ReportPropertyChanging("ExternalUrl");
                _ExternalUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExternalUrl");
                OnExternalUrlChanged();
            }
        }
        private global::System.String _ExternalUrl;
        partial void OnExternalUrlChanging(global::System.String value);
        partial void OnExternalUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemTitle
        {
            get
            {
                return _ItemTitle;
            }
            set
            {
                OnItemTitleChanging(value);
                ReportPropertyChanging("ItemTitle");
                _ItemTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemTitle");
                OnItemTitleChanged();
            }
        }
        private global::System.String _ItemTitle;
        partial void OnItemTitleChanging(global::System.String value);
        partial void OnItemTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemAbstract
        {
            get
            {
                return _ItemAbstract;
            }
            set
            {
                OnItemAbstractChanging(value);
                ReportPropertyChanging("ItemAbstract");
                _ItemAbstract = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemAbstract");
                OnItemAbstractChanged();
            }
        }
        private global::System.String _ItemAbstract;
        partial void OnItemAbstractChanging(global::System.String value);
        partial void OnItemAbstractChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemText
        {
            get
            {
                return _ItemText;
            }
            set
            {
                OnItemTextChanging(value);
                ReportPropertyChanging("ItemText");
                _ItemText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemText");
                OnItemTextChanged();
            }
        }
        private global::System.String _ItemText;
        partial void OnItemTextChanging(global::System.String value);
        partial void OnItemTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FeedModel", "FK_Item_ItemType", "ItemType")]
        public ItemType ItemType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemType>("FeedModel.FK_Item_ItemType", "ItemType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemType>("FeedModel.FK_Item_ItemType", "ItemType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ItemType> ItemTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ItemType>("FeedModel.FK_Item_ItemType", "ItemType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ItemType>("FeedModel.FK_Item_ItemType", "ItemType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FeedModel", "FK_ItemTag_Item", "ItemTag")]
        public EntityCollection<ItemTag> ItemTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ItemTag>("FeedModel.FK_ItemTag_Item", "ItemTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ItemTag>("FeedModel.FK_ItemTag_Item", "ItemTag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FeedModel", Name="ItemTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemTag object.
        /// </summary>
        /// <param name="ownerID">Initial value of the OwnerID property.</param>
        /// <param name="tag">Initial value of the Tag property.</param>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        public static ItemTag CreateItemTag(global::System.Guid ownerID, global::System.String tag, global::System.Guid itemID)
        {
            ItemTag itemTag = new ItemTag();
            itemTag.OwnerID = ownerID;
            itemTag.Tag = tag;
            itemTag.ItemID = itemID;
            return itemTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private global::System.Guid _OwnerID;
        partial void OnOwnerIDChanging(global::System.Guid value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                if (_Tag != value)
                {
                    OnTagChanging(value);
                    ReportPropertyChanging("Tag");
                    _Tag = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Tag");
                    OnTagChanged();
                }
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Guid _ItemID;
        partial void OnItemIDChanging(global::System.Guid value);
        partial void OnItemIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FeedModel", "FK_ItemTag_Item", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("FeedModel.FK_ItemTag_Item", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("FeedModel.FK_ItemTag_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("FeedModel.FK_ItemTag_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("FeedModel.FK_ItemTag_Item", "Item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FeedModel", Name="ItemType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ItemType object.
        /// </summary>
        /// <param name="itemTypeID">Initial value of the ItemTypeID property.</param>
        /// <param name="itemTypeName">Initial value of the ItemTypeName property.</param>
        public static ItemType CreateItemType(global::System.Byte itemTypeID, global::System.String itemTypeName)
        {
            ItemType itemType = new ItemType();
            itemType.ItemTypeID = itemTypeID;
            itemType.ItemTypeName = itemTypeName;
            return itemType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ItemTypeID
        {
            get
            {
                return _ItemTypeID;
            }
            set
            {
                if (_ItemTypeID != value)
                {
                    OnItemTypeIDChanging(value);
                    ReportPropertyChanging("ItemTypeID");
                    _ItemTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemTypeID");
                    OnItemTypeIDChanged();
                }
            }
        }
        private global::System.Byte _ItemTypeID;
        partial void OnItemTypeIDChanging(global::System.Byte value);
        partial void OnItemTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemTypeName
        {
            get
            {
                return _ItemTypeName;
            }
            set
            {
                OnItemTypeNameChanging(value);
                ReportPropertyChanging("ItemTypeName");
                _ItemTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ItemTypeName");
                OnItemTypeNameChanged();
            }
        }
        private global::System.String _ItemTypeName;
        partial void OnItemTypeNameChanging(global::System.String value);
        partial void OnItemTypeNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FeedModel", "FK_Item_ItemType", "Item")]
        public EntityCollection<Item> Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("FeedModel.FK_Item_ItemType", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("FeedModel.FK_Item_ItemType", "Item", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
