ALTER TABLE [dbo].[ItemPermission]
    ADD CONSTRAINT [PK_ItemPermission] PRIMARY KEY CLUSTERED ([ItemID] ASC, [RoleType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

