ALTER TABLE [dbo].[ItemHistory]
    ADD CONSTRAINT [PK_ItemHistory] PRIMARY KEY CLUSTERED ([ItemID] ASC, [RevisionDate] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

