ALTER TABLE [dbo].[ItemPermissionSpecificUser]
    ADD CONSTRAINT [PK_ItemPermissionSpecificUser] PRIMARY KEY CLUSTERED ([ItemID] ASC, [UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

