ALTER TABLE [dbo].[FriendInfo]
    ADD CONSTRAINT [PK_FriendInfo] PRIMARY KEY CLUSTERED ([UserID] ASC, [FriendID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

