//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace endnote.Tests.ContentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/Notenet.Content.DataContract")]
    [System.SerializableAttribute()]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagText {
            get {
                return this.TagTextField;
            }
            set {
                if ((object.ReferenceEquals(this.TagTextField, value) != true)) {
                    this.TagTextField = value;
                    this.RaisePropertyChanged("TagText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Notenet.Content.DataContract")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private endnote.Tests.ContentServiceReference.ItemContent ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemAbstractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public endnote.Tests.ContentServiceReference.ItemContent Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemAbstract {
            get {
                return this.ItemAbstractField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemAbstractField, value) != true)) {
                    this.ItemAbstractField = value;
                    this.RaisePropertyChanged("ItemAbstract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ItemID {
            get {
                return this.ItemIDField;
            }
            set {
                if ((this.ItemIDField.Equals(value) != true)) {
                    this.ItemIDField = value;
                    this.RaisePropertyChanged("ItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemTitle {
            get {
                return this.ItemTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTitleField, value) != true)) {
                    this.ItemTitleField = value;
                    this.RaisePropertyChanged("ItemTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemContent", Namespace="http://schemas.datacontract.org/2004/07/Notenet.Content.DataContract")]
    [System.SerializableAttribute()]
    public partial class ItemContent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalUrl {
            get {
                return this.ExternalUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalUrlField, value) != true)) {
                    this.ExternalUrlField = value;
                    this.RaisePropertyChanged("ExternalUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalUrl {
            get {
                return this.InternalUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalUrlField, value) != true)) {
                    this.InternalUrlField = value;
                    this.RaisePropertyChanged("InternalUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemText {
            get {
                return this.ItemTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemTextField, value) != true)) {
                    this.ItemTextField = value;
                    this.RaisePropertyChanged("ItemText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContentServiceReference.IContent")]
    public interface IContent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContent/GetUserTagList", ReplyAction="http://tempuri.org/IContent/GetUserTagListResponse")]
        endnote.Tests.ContentServiceReference.Tag[] GetUserTagList(System.Guid UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContent/GetUserTagItemList", ReplyAction="http://tempuri.org/IContent/GetUserTagItemListResponse")]
        endnote.Tests.ContentServiceReference.Item[] GetUserTagItemList(System.Guid UserID, string Tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContent/GetUserItemContent", ReplyAction="http://tempuri.org/IContent/GetUserItemContentResponse")]
        endnote.Tests.ContentServiceReference.ItemContent GetUserItemContent(System.Guid UserID, System.Guid ItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContent/Test", ReplyAction="http://tempuri.org/IContent/TestResponse")]
        string Test(System.Guid UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContentChannel : endnote.Tests.ContentServiceReference.IContent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentClient : System.ServiceModel.ClientBase<endnote.Tests.ContentServiceReference.IContent>, endnote.Tests.ContentServiceReference.IContent {
        
        public ContentClient() {
        }
        
        public ContentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public endnote.Tests.ContentServiceReference.Tag[] GetUserTagList(System.Guid UserID) {
            return base.Channel.GetUserTagList(UserID);
        }
        
        public endnote.Tests.ContentServiceReference.Item[] GetUserTagItemList(System.Guid UserID, string Tag) {
            return base.Channel.GetUserTagItemList(UserID, Tag);
        }
        
        public endnote.Tests.ContentServiceReference.ItemContent GetUserItemContent(System.Guid UserID, System.Guid ItemID) {
            return base.Channel.GetUserItemContent(UserID, ItemID);
        }
        
        public string Test(System.Guid UserID) {
            return base.Channel.Test(UserID);
        }
    }
}
